# (Phase-5-Backend) root@DESKTOP-HAIIK4K:~/Development/code/phase-5/project/Phase-5-Backend# python3 seed.py
# Traceback (most recent call last):
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2120, in _exec_insertmany_context
#     dialect.do_execute(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
#     cursor.execute(statement, parameters)
# psycopg2.errors.ForeignKeyViolation: insert or update on table "users" violates foreign key constraint "fk_users_coach_id_coaches"
# DETAIL:  Key (coach_id)=(1) is not present in table "coaches".


# The above exception was the direct cause of the following exception:

# Traceback (most recent call last):
#   File "/root/Development/code/phase-5/project/Phase-5-Backend/seed.py", line 207, in <module>
#     db.session.commit()
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
#     return self._proxied.commit()
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
#     trans.commit(_to_root=True)
#   File "<string>", line 2, in commit
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
#     ret_value = fn(self, *arg, **kw)
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
#     self._prepare_impl()
#   File "<string>", line 2, in _prepare_impl
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
#     ret_value = fn(self, *arg, **kw)
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
#     self.session.flush()
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
#     self._flush(objects)
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
#     with util.safe_reraise():
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
#     raise exc_value.with_traceback(exc_tb)
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
#     flush_context.execute()
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
#     rec.execute(self)
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
#     util.preloaded.orm_persistence.save_obj(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
#     _emit_insert_statements(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1143, in _emit_insert_statements
#     result = connection.execute(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
#     return meth(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
#     return connection._execute_clauseelement(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
#     ret = self._execute_context(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
#     return self._exec_insertmany_context(dialect, context)
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2128, in _exec_insertmany_context
#     self._handle_dbapi_exception(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
#     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2120, in _exec_insertmany_context
#     dialect.do_execute(
#   File "/root/.local/share/virtualenvs/Phase-5-Backend-4UYRDBFy/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
#     cursor.execute(statement, parameters)
# sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "users" violates foreign key constraint "fk_users_coach_id_coaches"
# DETAIL:  Key (coach_id)=(1) is not present in table "coaches".

# [SQL: INSERT INTO users (username, email, _password_hash, photo, coach_id) SELECT p0::VARCHAR, p1::VARCHAR, p2::VARCHAR, p3::VARCHAR, p4::INTEGER FROM (VALUES (%(username__0)s, %(email__0)s, %(_password_hash__0)s, %(photo__0)s, %(coach_id__0)s, 0), (%(user ... 997 characters truncated ...  imp_sen(p0, p1, p2, p3, p4, sen_counter) ORDER BY sen_counter RETURNING users.id, users.id AS id__1]
# [parameters: {'_password_hash__0': '$2b$12$AZD.erdvVUUalMwjw6PUQugLyniuBck58V0mM4jBw3luSRpUL1DRW', 'email__0': 'jane_doe@gmail.com', 'photo__0': 'https://images.pexels.com/photos/864939/pexels-photo-864939.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__0': 'jane_doe', 'coach_id__0': 1, '_password_hash__1': '$2b$12$5LkTGTnGxmvpvCPFGdNfAOiH1rO6vurSwvhynlxRJzgNHvuoxoIOq', 'email__1': 'michael_smith@gmail.com', 'photo__1': 'https://images.pexels.com/photos/791764/pexels-photo-791764.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__1': 'michael_smith', 'coach_id__1': 2, '_password_hash__2': '$2b$12$PgIB4ve.dpMvTG4Pj6Z5p.X0y5R.nKiYVfa0My1nmt9O5rLFF53Gu', 'email__2': 'emily_jones@gmail.com', 'photo__2': 'https://images.pexels.com/photos/1886487/pexels-photo-1886487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__2': 'emily_jones', 'coach_id__2': 3, '_password_hash__3': '$2b$12$x5jyAUbc4lQBj8miT9g3PO4.VTnfJCH2Q18ZbB.KndGzSabcv0IEW', 'email__3': 'daniel_wilson@gmail.com', 'photo__3': 'https://images.pexels.com/photos/1552102/pexels-photo-1552102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__3': 'daniel_wilson', 'coach_id__3': 4, '_password_hash__4': '$2b$12$KvvyCKewAcVeIi9/.vjJWO0bMB674o6EBpPJXTqdXgKvTl5g3zPiK', 'email__4': 'olivia_martin@gmail.com', 'photo__4': 'https://images.pexels.com/photos/863935/pexels-photo-863935.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__4': 'olivia_martin', 'coach_id__4': 5, '_password_hash__5': '$2b$12$ossc1N52du8B72V6LTVbGekScsjbdjpqR5RytyvarY2usFzG/jtSK', 'email__5': 'liam_anderson@gmail.com', 'photo__5': 'https://images.pexels.com/photos/2149771/pexels-photo-2149771.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__5': 'liam_anderson', 'coach_id__5': 1, '_password_hash__6': '$2b$12$.d/0N8iDrYfYBKhDXgvVxOKhbo3PL2OBs/Qtpwa19SaYoZgfhn9i6', 'email__6': 'ava_thomas@gmail.com', 'photo__6': 'https://images.pexels.com/photos/3757941/pexels-photo-3757941.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__6': 'ava_thomas', 'coach_id__6': 2, '_password_hash__7': '$2b$12$u.qeVQBt.LQ0J908bLiYE.jNYc4xKgldKCK6cH7SIHFTFZI7tMOLm', 'email__7': 'noah_taylor@gmail.com', 'photo__7': 'https://images.pexels.com/photos/4720309/pexels-photo-4720309.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__7': 'noah_taylor', 'coach_id__7': 3, '_password_hash__8': '$2b$12$2mgXqucl87ZQRf4Qk7nX9.XvdNzjfrMhfx06UNEzgC/wUTRH7ph8i', 'email__8': 'sophia_white@gmail.com', 'photo__8': 'https://images.pexels.com/photos/25034152/pexels-photo-25034152/free-photo-of-woman-doing-deadlifts-in-the-gym.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__8': 'sophia_white', 'coach_id__8': 4, '_password_hash__9': '$2b$12$ySfbu.rkxMzkp1v.8Jcaq.hNR4rIfBoyfXwLpXIKBHIqAx8RkubNi', 'email__9': 'benjamin_harris@gmail.com', 'photo__9': 'https://images.pexels.com/photos/6389075/pexels-photo-6389075.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__9': 'benjamin_harris', 'coach_id__9': 5, '_password_hash__10': '$2b$12$2mTu6Ho7u69edrNvZSGPhuiaxCEPSygDAOXLZoTSWSFHfejx49dVy', 'email__10': 'chris_evans@gmail.com', 'photo__10': 'https://images.pexels.com/photos/241456/pexels-photo-241456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__10': 'chris_evans', 'coach_id__10': 6, '_password_hash__11': '$2b$12$PXBdGUnndqtQI.zi.n8n1OfTDGw7By76bthggQ.aJSI1G5J4y1JSS', 'email__11': 'natalie_portman@gmail.com', 'photo__11': 'https://images.pexels.com/photos/1552249/pexels-photo-1552249.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'username__11': 'natalie_portman', 'coach_id__11': 6}]
# (Background on this error at: https://sqlalche.me/e/20/gkpj)